### ISSUE TITLE
500 as hiba

### ISSUE THREAD

**Issue by azbuco** [pzs/nav-online-invoice#10]
Helló! Szuper a programod, és ne haragudj hogy ilyennel zavarlak, de érdekel,  hogy valaki találkozott-e ezzel:

A 2018.08.01-et követő navos frissítés után, a teszt rendszerbe küldött számlákra (és csak a teszt rendszerbe, ugyanaz az éles rendszerbe küldve simán megy) 500 as hibát kapok, ezzel az üzenettel: An HTTP protocol violation was detected and your request was denied. 

A navos tudástár szerint "Ezt az üzenetet a szerver előtt lévő hálózatvédelmi eszköz adja vissza akkor, ha a HTTP kérés nem engedélyezett endpointra érkezett. (pl. a POST után hibás vagy hiányzik az URL) Ellenőrizni kell a kimenő HTTP üzenetet!", de nem igazán értem, hogy akkor az élesben miért megy, illetve az összes többi endpointra menő kérésre miért jön normális válasz.

Esetleg másnál is jelentkezik ez?

**Comment by pzs** [comment]
Szia! Köszi a hibajelentést! prog.hu-s fórum alapján javítva és friss verziót is készítettem. Release notes: https://github.com/pzs/nav-online-invoice/releases/tag/v0.7.1

Továbbá én is meg tudom erősíteni, hogy teszt rendszeren nem ment, élesen viszont igen.
