### ISSUE TITLE
Számla sztornózása

### ISSUE THREAD

**Issue by kotapeter** [pzs/nav-online-invoice#13]
@pzs Eloszor is koszi a fejlesztes, nagyon hasznos ez a csomag! :)

Van esetleg pelda xml/kod arra, hogy szamlat hogyan lehet sztornozni?

Koszi!

**Comment by pzs** [comment]
Szia @kotapeter ,

Bővítettem a README manageInvoice() részét ezzel kapcsolatban: https://github.com/pzs/nav-online-invoice#reporter-oszt%C3%A1ly

Röviden, ha egy számlával hívod a manageInvoice() metódust, akkor `operation` paraméterként (2. paraméter) "STORNO" értéket kell átadnod "CREATE" helyett, ahogy az definiálva van a NAV-os specifikációban.
Példa: https://github.com/pzs/nav-online-invoice/blob/master/examples/manageInvoice_simple.php#L12 (itt a "CREATE" helyett kell a "STORNO").
