### ISSUE TITLE
2.0-ás interfész verzióra frissítés

### ISSUE THREAD

**Issue by webprogramozo** [pzs/nav-online-invoice#14]
Üdv!

Tervben van a library frissítése/továbbfejlesztése, hogy támogassa a 2.0-ás interfész verziót?

**Comment by pzs** [comment]
Szia!

Igen, mindenképpen tervben van még várhatóan ebben az évben. (Mi is használjuk ezt az interfészt.)

**Comment by webprogramozo** [comment]
Szuper! Köszi a visszajelzést! :)
