### ISSUE TITLE
Hiányzó invoice_annul.xml file

### ISSUE THREAD

**Issue by azbuco** [pzs/nav-online-invoice#15]
Helló!

Csak egy apró észrevétel:
A példák közt, a  manageInvoice_annul.php fájlban hivatkozol az invoice_annul.xml fájlra, ami viszont nem található a testdata könyvtárban.

**Comment by pzs** [comment]
Szia,

köszönöm az észrevételt. Jogos, de a példafájl célja itt csak az interfész használatának bemutatása, nem pedig a számla xml-re példa adás. Utóbbit NAV-os példafájlok között meg lehet találni.

Ezen oknál fogva ezt az issue-t lezárom, de a 2.0-ás interfész fejlesztése folyamán frissíteni fogom a példafájlokat ezzel a javítással is.
