### ISSUE TITLE
2.0-ás interfész támogatása

### ISSUE THREAD

**Issue by pzs** [pzs/nav-online-invoice#16]
A NAV kiadta a 2.0-ás XML API leírást, melyre az átállást jelenlegi információk szerint 2020.04.01-ig kötelezően meg kell tenni.

Információ a [hivatalos](https://onlineszamla.nav.gov.hu/) oldalról:

> A 2.0 számlabejelentő interfész 2019 évben csak tesztkörnyezetben működik, az éles környezetben leghamarabbi használatbavétel 2020. február hónapra prognosztizálható. Ennek pontos időpontjáról tájékoztatást teszünk közzé.
> 
> A 2.0 számlabejelentő interfész mindenki számára kötelező átállásának időpontja 2020.04.01 00:00 óra. Ettől az időponttól kezdődően a korábbi verzió (1.1) szerinti adatszolgáltatás nem teljesíthető.

Jelen nav-online-invoice PHP-s interfész 2.0-ás API-ra való felkészítését 2019. legvégére tervezem elkészíteni, hogy utána elegendő idő legyen beépíteni a számlázó programokba is.

**Comment by pzs** [comment]
**:mega: Elkészült a 2.0-ás API-t támogató interfész RC verziója.**

Ez a verzió teljes mértékben támogatja a jelenleg elérhető 2.0-ás interfészt, de még nem jelöltem végleges verziónak, mert:
- további fejlesztések várhatóak a NAV részéről, így bővülni fog ez a modul is, illetve
- éles környezetben még nem elérhető a NAV 2.0-ás API.

Amennyiben a NAV 2.0-ás API-jára meg szeretnéd kezdeni az átállást, kérlek, használd ezen modul [2.0.0-ás RC/pre-release](https://github.com/pzs/nav-online-invoice/releases) verzióját. Frissített leírást és példafájlokat megtalálod a [2.0-ás branch](https://github.com/pzs/nav-online-invoice/tree/2.0) alatt, illetve [packagist](https://packagist.org/packages/pzs/nav-online-invoice)-ről is letölthető a `v2.0.0-RC1` verzió.

Ezt az issue-t nyitva hagyom egész addig, amíg a NAV nem teszi éles környezetben is elérhetővé a 2.0-ás API-t, s ezzel együtt nem adom ki én is a modul végleges 2.0.0-ás verzióját.

**Comment by KisstiKft** [comment]
Sajnos én még az 1.1 nél elakadtam. A 0 illetve TAM ... tételeket nem tudom felvenni az XML .be.
tudna egy ilyen példa xml-t felrakni?

**Comment by pzs** [comment]
Szia, ez a modul a NAV és a számlázó program közti kapcsolatban segít, a szakmai XML összeállítás nem feladata. Ezzel kapcsolatban más fórumon tudsz segítséget kérni.

**Comment by KisstiKft** [comment]
Köszönöm a segítségét. Tamáspzs <notifications@github.com> ezt írta (2020. jan. 29. 22:19):Szia, ez a modul a NAV és a számlázó program közti kapcsolatban segít, a szakmai XML összeállítás nem feladata. Ezzel kapcsolatban más fórumon tudsz segítséget kérni.

**Comment by KisstiKft** [comment]
El kezdtem tesztelni a 2.0 verziót.
Az adószám ellenőrzésnél (queryTaxpayer.php) csak a nevet adja vissza, más adat (cím) nincs.

**Comment by pzs** [comment]
Jelenlegi információk szerint hamarosan még egy frissítés csomag várható a NAV oldaláról a 2.0-ás API-hoz, melyhez ezt a modult március első hetében fogom tudni hozzáilleszteni, így a végleges verzió (ebből a PHP-s interface-ből) március 2-8. között várható.

**Comment by pzs** [comment]
Elkészült a végleges 2.0.0-ás modul, bővebb információért lásd a [release notes](https://github.com/pzs/nav-online-invoice/releases/tag/v2.0.0)-ot, illetve a [README](https://github.com/pzs/nav-online-invoice)-t.

**Comment by KisstiKft** [comment]
Tisztelt uram!

 

Sajnos az "queryTaxpayer" még mindig nem működik.

 

Az adószámhoz tartozó név: KISSTI SZÁMÍTÁSTECHNIKAI ÉS SZÁMVITELI KFT.
További lehetséges információk az adózóról: SimpleXMLElement Object ( )
SimpleXMLElement Object ( ) SimpleXMLElement Object ( ) SimpleXMLElement
Object ( [taxpayerAddressItem] => SimpleXMLElement Object (
[taxpayerAddressType] => HQ [taxpayerAddress] => SimpleXMLElement Object ( )
) )

 

Tisztelettel Kiss Tamás

  _____
