### ISSUE TITLE
Stornó számla probléma

### ISSUE THREAD

**Issue by joeprog** [pzs/nav-online-invoice#19]
Az lenne a problémám a 2.0-val, hogy ha STORNO operation-t adok ki és megadom az eredeti számla hivatkozást, akkor a NAV visszadobja ezzel a hibaüzenettel.

INVOICE_REFERENCE_NOT_EXPECTED
Eredeti számlára történő hivatkozás alapszámla esetén nem adható meg.

Megnéztem és a operation-nél STORNO szerepel és nem CREATE.
Mi lehet szerinted a gond?

**Comment by pzs** [comment]
A szakmai XML-ed nem stimmel (invoiceReference-t máshova kell beszúrni, lásd NAV-os leírásokat), tehát nem maga a `nav-online-invoice` modulban van a hiba.
