### ISSUE TITLE
queryTaxpayer és xml namespace-ek

### ISSUE THREAD

**Issue by pzs** [pzs/nav-online-invoice#20]
[Ezen commit](https://github.com/pzs/nav-online-invoice/commit/0cb3d6d40e111d612d7537bd93561798453846b7#comments) alatt elkezdett beszélgetést hoznám át külön ticket alá. Eredeti probléma, ahogy @ptack leírta, hogy a `queryTaxpayer` xml válaszában egyes elemek `ns2` namespace alatt szerepelnek, amit körülményesebb kiolvasni.

Egy XML válasz:
```xml
   <taxpayerData>
      <taxpayerName>MINTA BOLT KFT.</taxpayerName>
      <taxNumberDetail>
         <ns2:taxpayerId>12345678</ns2:taxpayerId>
         <ns2:vatCode>1</ns2:vatCode>
      </taxNumberDetail>
      <taxpayerAddressList>
         <taxpayerAddressItem>
            <taxpayerAddressType>HQ</taxpayerAddressType>
            <taxpayerAddress>
               <ns2:countryCode>HU</ns2:countryCode>
               <ns2:postalCode>1112</ns2:postalCode>
               <ns2:city>BUDAPEST</ns2:city>
               <ns2:streetName>....</ns2:streetName>
               <ns2:publicPlaceCategory>....</ns2:publicPlaceCategory>
               <ns2:number>....</ns2:number>
               <ns2:floor>....</ns2:floor>
               <ns2:door>....</ns2:door>
            </taxpayerAddress>
         </taxpayerAddressItem>
      </taxpayerAddressList>
   </taxpayerData>
```

Ezt célszerű lenne még a `nav-online-invoice` modulban átalakítani annak érdekében, hogy könnyebben fel lehessen dolgozni. Erre felmerült ötlet:
- a modul automatikusan eltávolítaná az `ns2:` namespace-t, s a válasz maradna továbbra is xml object, vagy
- a modul automatikusan tömbbé alakítaná az xml válaszokat és a különböző namespace alatt lévő elemeket összefűzné, lásd itt: https://stackoverflow.com/a/26415387 . Így a visszatérési érték `Array` lenne XML elem helyett. Ez lehet könnyebben kezelhető, viszont nem konzisztens a többi metódussal. Minden átalakítása pedig nagyon breaking change lenne.

Jelenleg az 1. megoldás felé hajlok, amit opcionálisan ki lehetne kapcsolni, viszont kíváncsi vagyok visszajelzésekre is.

**Comment by attilafabian** [comment]
Hasznos ötletnek tartom. Nekem is az 1. megoldás a szimpatikusabb.

**Comment by pzs** [comment]
Köszönöm a visszajelzést, el is készítettem ezt az 1. megoldást. Részletek a release notes-ban: [v2.0.1](https://github.com/pzs/nav-online-invoice/releases/tag/v2.0.1)

**Comment by KisstiKft** [comment]
Nagyon hasznos lenne ha az adószám megye kódja (countyCode) és a kiállító rövid neve (ShortName) elérhető lenne.
Az adózó többi címe is elérhető lesz a array-ban?

**Comment by pzs** [comment]
Ez nem ezen a modulon múlik, hanem azon, hogy a NAV mit ad vissza.

**Comment by jutacoder** [comment]
Szia,
a queryTaxpayer operáció nem müködik és a ns2: miatt.
Ezt a kódot használom: https://github.com/pzs/nav-online-invoice/releases/tag/v2.0.1
Ahogy látom a $removeNamespaces nincs használva.

**Comment by jutacoder** [comment]
Szia,  
Elnéztem,  a  removeNamespaces  használva van, a hiba nálam van valahol.

**Comment by pzs** [comment]
Alapértelmezetten törölve van az "ns2:", szóval ezzel neked nem is kell(ene) foglalkozni, illetve nem igényel plusz beállítást.
