### ISSUE TITLE
Adószám ellenőrzés a nav válasz xml-ben ha false, akkor sem tér vissza false-al, hanem érvényesnek mutatja. 

### ISSUE THREAD

**Issue by GaBbB** [pzs/nav-online-invoice#24]
https://github.com/pzs/nav-online-invoice/blob/e555baefa51785957bf975c0ee58382b4e4442fa/src/NavOnlineInvoice/Reporter.php#L216

php 7.0, és 7.4-es verzió alatt az ebben a sorban található feltétel nem fogja meg, hogy érvényes-e az adószám, a visszatérési érték pedig csak az adózó adatait tartalmazza.  Ezzel az adószámmal tudjátok tesztelni: 68833109

**Comment by pzs** [comment]
Szia,
nálam a kérdéses adószámra azt hozza, hogy érvényes PHP 7.2 és 7.4 alatt (nav test rendszer). Érvénytelen lenne? Vagy mi pontosan a hiba?

**Comment by GaBbB** [comment]
Igen, ez egy érvénytelen adószám. Az éles nav rendszere a taxpayerValidity-t false-al adja vissza, viszont a kód nem fogja meg és visszaadja az adózó adatait, pedig false-al kéne visszatérnie.

**Comment by GaBbB** [comment]
Emiatt most így péntek délután beleírtam egy tákolást (most ennyire tellett hirtelen), hogy átalakítom tömbbé az xml választ és úgy ellenőrzöm, mert éles rendszeren becsúszott 2 ilyen számla. Csak gondoltam jelzem, hogy másnál se fordulhasson elő.

**Comment by pzs** [comment]
Köszi a jelentést! Valóban, ha az adózó létezett valaha, de időközben érvénytelenné vált az adószám, akkor is visszatért az adózó adataival. Ezt most javítottam, szóval ez esetben `false` a visszatérési érték, ahogy az a README-ben is szerepel.
Javított verzió: https://github.com/pzs/nav-online-invoice/releases/tag/v2.0.3
