### ISSUE TITLE
Timestamp Issue

### ISSUE THREAD

**Issue by arnyee** [pzs/nav-online-invoice#3]
Szia, nagyon tetszik a csomag a NAV kommunikációjához, nagyon hasznos és könnyen használható, hatalmas segítség.

Egy hibát sikerült felfedezni benne, remélem tudsz benne segíteni, ha jól értem az időbélyeg formátumával van, el is küldöm a hibaüzenetet:

NavOnlineInvoice\XsdValidationError: Error: Element '{http://schemas.nav.gov.hu/OSA/1.0/api}timestamp': [facet 'pattern'] The value '2018-05-31T13:54:55.1000Z' is not accepted by the pattern '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z'.

Error: Element '{http://schemas.nav.gov.hu/OSA/1.0/api}timestamp': '2018-05-31T13:54:55.1000Z' is not a valid value of the atomic type '{http://schemas.nav.gov.hu/OSA/1.0/data}TimestampType'.

Ez az időpont a számla beküldésének időpontja, amit nem az általam összerakott xml tartalmaz, leellenőriztem és ugye az a baj, hogy a formázott timestamp végén az 1000Z nem felel meg a d{3}Z -nek.

Ma ezt a számlát újból elküldtem még egyszer és simán átment. Esetleg erre van valami ötleted hogy miként lehetne megoldani, hogy a jövőben ez ne fordulhasson elő? A válaszodat és a segítséget előre is köszönöm!

**Comment by pzs** [comment]
Szia! Köszi a jelentést! x.9995 és x.9999 tízezred másodpercnél 1000-re kerekített fel, szóval kis esély volt hibás timestamp generálására, de ez most javítva a v0.4.1 verziótól.
