### ISSUE TITLE
Lesz v3.0-s API támogatás?

### ISSUE THREAD

**Issue by pedrolovara** [pzs/nav-online-invoice#30]
Szeretném kérdezni, hogy terveztitek-e a 3.0-s API-ra is elkészíteni ezt a PHP-s csomagot.

**Comment by pzs** [comment]
Igen, még ebben a hónapban tervezem publikálni.

**Comment by simisoma** [comment]
Köszönet érte!

> 2020. okt. 17. dátummal, 9:06 időpontban pzs <notifications@github.com> írta:
> 
> en a hónapban tervezem publikálni.

**Comment by pedrolovara** [comment]
Előre is köszönjük, óriási segítség ez.

**Comment by pzs** [comment]
El is készült a 3.0-ás API támogatás :)

Leírás: https://github.com/pzs/nav-online-invoice/releases/tag/v3.0.0-RC1

A `v3.0.0-RC1` release véglegesnek tekinthető és integrálható/tesztelhető. `v3.0.0`-ás verziószámmal várhatóan egy hónap múlva készítek el egy újabb release-t további tesztelések és szükség szerinti hibajavítások után -- szóval bármi hibát észleltek a modullal kapcsolatban, jelezzétek.

Ezt az issue-t nyitva hagyom a `v3.0.0`-as release elkészítéséig.

**Comment by pedrolovara** [comment]
Hú, ez gyors volt, köszönjük :-)

**Comment by pzs** [comment]
A NAV mai nap frissítette a teszt rendszerét új verzióval, mely új XSD-t is takar, így ezen modulból is készült új verzió: [v3.0.0-RC2](https://github.com/pzs/nav-online-invoice/releases/tag/v3.0.0-RC2)

Más változtatásra már nem számítok, így amint elérhető lesz a 3.0-ás interface az éles környezeten is, úgy kiadásra kerül ebből a modulból is a végleges verzió. Ez tartalmilag meg fog egyezni a mostani, RC2-es verzióval, szóval bátran használható ez a verzió fejlesztéshez.

**Comment by pzs** [comment]
Elkészítettem a végleges 3.0.0-ás release-t, ami megegyezik az előző RC2-es változattal. Nálam eddig működik a NAV-os teszt interface-en és remélhetőleg, most már más változtatásra nem kell számítani :)

Letöltés: https://github.com/pzs/nav-online-invoice/releases/tag/v3.0.0

Ezzel zárom ezt az issue-t.
