### ISSUE TITLE
QueryInvoiceDataRequestXml - hiba ha a számlaszám tartalmaz speciális karaktert mint pl a a "&"

### ISSUE THREAD

**Issue by Volfid** [pzs/nav-online-invoice#34]
Szeretném jelezni, hogy az src/QueryInvoiceDataRequestXml nem tudja kezelni a címben is jelzett speciális karaktert, mivel a $node->addChild($key, $value); ilyenkor üres értéket ad az invoiceNumber elemnek. Ezt meg lehet kerülni úgy, hogy a $node->invoiceNumber = $value; -t használjuk.

**Comment by pzs** [comment]
Köszi az észrevételt, javítottam v3-as verzióban! Mostantól nem az addChild() van használva, mert ez nem escapeli az & jelet.
