### ISSUE TITLE
queryInvoiceData lekérdezésnél: PHP Notice:  Undefined variable: invoice in

### ISSUE THREAD

**Issue by cityba** [pzs/nav-online-invoice#35]
Szia, egy több tételes számla lekérdezésnél kapom ezt a hibaüzenetet.
PHP Notice:  Undefined variable: invoice in... és a var_dump()ra mutat,
Mi lehet a hiba? 2-3 soros számlánál nincs hiba.
ezt kapom : NavOnlineInvoice\HttpResponseError: (HTTP Status code: 200)NULL

**Comment by pzs** [comment]
Szia,
Tudnál kicsit részletesebb hibaüzenetet bemásolni? Vagy esetleg leírást, hogy tudom reprodukálni a hibát?
Az [examples/log.php](https://github.com/pzs/nav-online-invoice/blob/master/examples/log.php#L20-L25) példában látható, hogyan lehet a kérést/választ kiíratni.

**Comment by cityba** [comment]
Megoldás:  curl verzió min.: 7.68 és php-curl verzió min.: 7.4 , ezek alatt instabil a lekérdezés válasza.
