### ISSUE TITLE
Logolás

### ISSUE THREAD

**Issue by LBanfalvi** [pzs/nav-online-invoice#38]
Szia!

Köszi ezt a remek munkát! Egy kérésem hadd legyen, lehetséges, hogy legyen egy lastRequestXML a lastResponseXML-hez hasonlóan? Ha igen, el is tudnám dobni a fork-unkat...

**Comment by pzs** [comment]
Szia!

Örülök, ha használjátok :)
Ha csak debuggoláshoz/naplózáshoz kell, akkor ajánlanám a [$reporter->getLastRequestData()](https://github.com/pzs/nav-online-invoice/blob/master/src/NavOnlineInvoice/Connector.php#L39) metódust, ez visszaadja a requestBody-t is string-ként. Van egy példafájl is [itt](https://github.com/pzs/nav-online-invoice/blob/master/examples/log.php#L23).
Ha nem erre gondoltál, akkor kérdezném, hogy dedikált get metódusra lenne szükség, vagy pedig kifejezetten XML object-ként kell a request? Utóbbi esetében hozzáadnám a getLastRequestData()-hoz.

**Comment by LBanfalvi** [comment]
Szia, nem lenne baj, ha konzisztensek maradnánk az eddigi funkcionalitással, jelenleg így adjuk vissza minden eljárásból:

`public function queryInvoiceData($invoiceNumberQuery, &$rawRequestXml = NULL, &$rawResponseXml = NULL) {
        $requestXml = new QueryInvoiceDataRequestXml($this->config, $invoiceNumberQuery);
        $responseXml = $this->connector->post("/queryInvoiceData", $requestXml);
        
        if ($rawRequestXml!==NULL) $rawRequestXml=$requestXml->asXML();
        if ($rawResponseXml!==NULL) $rawResponseXml=$responseXml->asXML();

        return $responseXml->invoiceDataResult;
    }`

**Comment by pzs** [comment]
Ahogy nézem a bemásolt kódot a requestXml-t te is string formában adod vissza, csak máshol.

Ez nálam a modulban a fent említett getLastRequestData() metódussal érhető el, ahol ezen felül még több információ is elérhető (url, header, stb.). Más variációt nem szeretnék behozni.

**Comment by LBanfalvi** [comment]
Köszi, kipróbálom!
