### ISSUE TITLE
NAV 2020.12.01.-i XSD-k

### ISSUE THREAD

**Issue by LBanfalvi** [pzs/nav-online-invoice#39]
Szia!

A legutolsó (2020.12.01.) NAV 3.0 xsd-k eltérnek a jelenleg kódban levőktől, mikor tervezed kiadni az új verziót?

Köszönöm!

**Comment by pzs** [comment]
Szia,

amint frissítik a teszt környezetüket az új sémára, frissíteni fogom itt is a kódban, illetve készítek egy újabb release-t (az oka az, hogy szeretném tesztelni a frissítést, mielőtt azt commitálom/release-elem). Addig nyitva is hagyom ezt az issue-t, illetve, ha nem venném észre, mikor frissítenek, lehet írni itt :)

Ahogy nézem, nem csak az xsd-ket kell frissíteni, hanem passwordHash-nél a cryptoType-ot is át kell írni.

**Comment by pzs** [comment]
Új XSD-k elérhetők a legfrissebb verzióban: [v3.0.0-RC2](https://github.com/pzs/nav-online-invoice/releases/tag/v3.0.0-RC2)
Most már a nav teszt rendszere mögött is ez az XSD verzió van.
