### ISSUE TITLE
CurlError: Connection error. CURL error code: 60

### ISSUE THREAD

**Issue by simisoma** [pzs/nav-online-invoice#40]
Üdvözöllek,

 mindenek előtt én is nagyon köszönöm a 3.0 frissítést. 

A számlákat PHP 5.6 környezetben küldöm, és amióta felraktam a 3.0 verziót, ennyi hibaüzenetet ad vissza:

NavOnlineInvoice\CurlError: Connection error. CURL error code: 60

 Mi lehet a gond? A 2.0 simán ment eddig. :-(

Köszönöm!

**Comment by pzs** [comment]
Szia,

[3.0.0 release notes](https://github.com/pzs/nav-online-invoice/releases/tag/v3.0.0)-ban említettem, de lehet nem túl hangsúlyosan. Ez lesz a megoldás a fenti hiba esetén (ha certificate-ek beállítása nem opció):

Config osztályban a `$verifySSL` értéke alapértelmezetten `true` lett, így ha bármi rosszul beállított certificate miatt nem kapcsolódna a modul a NAV-hoz ("Connection error. CURL error code: 60" hibát kapnál), `$config->verifySSL = false;`-ra állításával ki tudod kapcsolni a `cURL`-ben az SSL ellenőrzést.

```php
$config = new NavOnlineInvoice\Config($apiUrl, $userData, $softwareData);
$config->setCurlTimeout(70); // 70 másodperces cURL timeout (NAV szerver hívásnál), opcionális
$config->verifySSL = false;

$reporter = new NavOnlineInvoice\Reporter($config);
```

(a másik, duplikált issue-t töröltem)

**Comment by simisoma** [comment]
Köszönöm! 

 Ez is megoldotta.
De nem vol ténylegesen fenn a cacert.pem file így le kellett töltenem és a php.ini-be beírni az elérhetőségét. ezzel is működött.

 Hálásan köszönöm!

**Comment by attilafabian** [comment]
Megjegyzés: 2023 január 5-én a NAV lecserélte a szerver tanusítványát. (Az új tanusítvány letölthető a https://onlineszamla.nav.gov.hu/dokumentaciok oldalról.) Január 5-én este és 6-án voltak problémák a tanusítványlánc küldésével kapcsolatban (CurlError: Connection error. CURL error code: 60), de 6-án estére a probléma megoldódott. Ha esetleg valaki kikapcsolta a verifySSL-t, akkor meg lehet próbálni visszakapcsolni ;)

**Comment by eszel** [comment]
Egy bejegyzést csinálhattak volna ebből az "Informatikai változások" menüpontban, hisz ez egy komoly változás, nem csak a dokumentációba betenni.. én magam kutattam ki, hogy milyen cert kell neki külső SSL elemző szerverrel..
