### ISSUE TITLE
Köszönet + szponzoráció kérdés

### ISSUE THREAD

**Issue by akos-torok-docca** [pzs/nav-online-invoice#42]
Szia pzs,

Nagyon köszönom azt, hogy ezt a projektet viszed, nagyon sokat segített nekem és a cégünknek! Lehet valahogyan anyagilag is támogatni azt, hogy te ezt csinálod? Szponzorság (https://github.com/sponsors), donation - vagy esetleg egyszerűen kiállítanál nekünk egy számlát egy megbeszélt összegről?

Üdv,

Ákos

**Comment by LBanfalvi** [comment]
Ezzel egyet értek, nekünk is roppant hasznos a munkásságod és szívesen honorálnánk.

Üdv:
Laci

**Comment by simisoma** [comment]
Üdvözöllek!

 Én is csatlakozom a fentiekhez, nagyon köszönöm a munkádat!!!!

Üdv: Soma

**Comment by pzs** [comment]
Sziasztok!

Szívesen és örülök, hogy ez ekkora segítséget jelent másoknak is :)
Szponzorációtól függetlenül foglalkozok a projekttel, de ha regisztrálnék funding/sponsoring platformon, akkor ki fogom tenni a linkjét. Addig esetleg a pzs.github@gmail.com címen elérhető vagyok.

üdv. pzs
