### ISSUE TITLE
Tanácskérés

### ISSUE THREAD

**Issue by utomi84** [pzs/nav-online-invoice#43]
Kedves pzs, először is köszönöm a fantasztikus munkádat, óriási segítség az amit csinálsz. Egyúttal egy kis tanácsot is kérnék. Lehetséges-e szerinted, hogy a munkádat egy Wordpress oldal alá tegyem be. A cél az lenne, hogy egy kattintással lekérhetőek legyenek az adatok egy egyszerű felületen keresztül. Esetleg tudnál tanácsot adni, hogyha szerinted megoldható, hogy merre induljak el? Nem vagyok teljesen sötétben de a php még nagyon új nekem. Előre is köszönöm szépen ha van időd válaszolni.

**Comment by pzs** [comment]
Szia! Lehetséges, bárhol felhasználhatod ezt a modult, de ha pl. csak a bejövő számlákat akarod lekérdezni, akkor azt a [nav](https://onlineszamla.nav.gov.hu/) felületén is meg tudod tenni. Csak a modul használatában tudok tanácsot adni, melyhez igyekeztem mindent leírni a [README](https://github.com/pzs/nav-online-invoice/blob/master/README.md)-ben, illetve ajánlom a példafájlokat is (pl. [ezt](https://github.com/pzs/nav-online-invoice/blob/master/examples/queryInvoiceDigest.php) a bejövő számlák lekérdezéséhez). Más egyéb kérdésben pedig a prog.hu-s fórumot ([NAV-os topic](https://prog.hu/tarsalgo/188874/adohatosagi-ellenorzesi-adatszolgaltatas-online-szamla)).

**Comment by utomi84** [comment]
Okés elkezdtem beleásni magam a példafájlokon keresztül. Eljutottam addig, hogy megadom a következő birtokomban lévő adatokat: technikai felhasználó a loginhez, xml kulcs a signKey-hez és XML cserekulcs az exchangeKey-hez. Viszont mivel technikai felhasználóként mennék be így ugye password nincs használatban. Tehát a passwordot nem írok be. Na most ilyenkor ezt a hibaüzenetet kapom vissza: NavOnlineInvoice\GeneralErrorResponse: Helytelen authentikációs adatok! (INVALID_SECURITY_USER). Nyilván én vagyok az idióta de tudnál segíteni, hogy mit nézek el. Próbáltam kilőni a passwordot de akkor is szinte ugyanez jön vissza: Notice: Undefined index: password in C:\xampp\htdocs\src\NavOnlineInvoice\BaseRequestXml.php on line 88
NavOnlineInvoice\GeneralErrorResponse: Helytelen authentikációs adatok! (INVALID_SECURITY_USER). Válaszodat előre is köszönöm.

**Comment by tsamu** [comment]
A technikai felhasználónak is van jelszava, amit a létrehozásakor kell megadni. Szívesen segítünk, de alapvető kérdéseket szerintem a prog.hu-s NAV-os topicban tegyél fel.

**Comment by utomi84** [comment]
> A technikai felhasználónak is van jelszava, amit a létrehozásakor kell megadni. Szívesen segítünk, de alapvető kérdéseket szerintem a prog.hu-s NAV-os topicban tegyél fel.

Rendben. Köszönöm akkor utána járok.

**Comment by utomi84** [comment]
> > A technikai felhasználónak is van jelszava, amit a létrehozásakor kell megadni. Szívesen segítünk, de alapvető kérdéseket szerintem a prog.hu-s NAV-os topicban tegyél fel.
> 
> Rendben. Köszönöm akkor utána járok.
 És bocsánat ha ez alapvető kérdés, igyekszem a jövőben erre jobban odafigyelni.
