### ISSUE TITLE
V 2.0 magánszemély számla minta

### ISSUE THREAD

**Issue by Mailmedve** [pzs/nav-online-invoice#44]
Kedves fejlesztők, kérlek segítsetek, hol találok egy mintát arról, hogy hogyan lehet a V 2 -vel beküldeni magánszemélynek kiállított számla adatokat?

**Comment by pzs** [comment]
<del>Szia!</del>

<del>A 2.x-es branchen ( https://github.com/pzs/nav-online-invoice/tree/2.x ) van a modul v2-es API változata, itt az [examples](https://github.com/pzs/nav-online-invoice/tree/2.x/examples) mappában vannak példák is.</del>

<del>Viszont megjegyezném, hogy a példák a v2 és v3 alatt is lényegében megegyeznek, mert a különbség nagy részét maga az nav-online-invoice modul elfedi. (Természetesen nem a számla/szakmai XML-re gondolok, hanem a $reporter metódusok hívása változatlan.)</del>

(törölve, lásd következő kommentet)

**Comment by tsamu** [comment]
Szerintem az XML customerInfora gondol. V2-ben a magánszemélyeknek kiáltott számlákra nincs adatszolgáltatási kötelezettség, ergo nem hiszem, hogy jó ötlet ezt használni magánszemélyre. A V2 customerInfoban egyébként csak a customerName és customerAddress kötelező, elvileg ha így küldöd be, akkor elfogadja. Az más kérdés, hogy az alábbi olvasható a v3 specifikációban:

2021 január 4-től a nem adóalany magánszemélyeknek kiállított számlák adatszolgáltatása is kötelező. Ilyen számlák esetén csak a magánszemély vevőtípus jelölése (customerVatStatus = PRIVATE_PERSON) kötelező, **semmilyen egyéb vevői adat nem szerepeltethető az adatszolgáltatásban**. Ettől a számlának kötelező adattartalma a magánszemély vevő neve, címe, ugyanakkor a számlaadattól ebben az esetben eltér az adatszolgáltatás tartalma. Ha a vevő magánszemély (customerVatStatus = PRIVATE_PERSON), akkor **az adóhivatali rendszer nem fogad be olyan adatszolgáltatást, mely tartalmaz vevői név és/vagy címadatot, bármi is szerepel ezekben a mezőkben**.

**Comment by pzs** [comment]
@tsamu , köszi a korrekciót! Csak a "beküldeni" szóig értelmeztem a kérdést :/
Magánszemély számlát csak v3-on lehet beküldeni.
