### ISSUE TITLE
Exception: SHA3-512 nem támogatott! 

### ISSUE THREAD

**Issue by endrus24** [pzs/nav-online-invoice#45]
Kedves Fejlesztő(k)! 

Először is nagyon köszönöm, hogy elkészítésre került a php-s verzió! XAMPP -ban pc-n tesztelve tökéletesen működik minden és a leírás is egyértelmű volt. Még egyszer szeretném megköszönni az áldozatos munkát.
A tesztelés során az alábbi probléma adódott amiben kérnék segítséget.
Mikor a szerveren futó webshop rendszerben próbáltam integrálni a modult a szerveren futó php beállítások miatt : PHP Version 5.6.40  az alábbi üzenetérkezett:

Exception: SHA3-512 nem támogatott! Kérlek, - frissíts PHP 7.1.0 vagy e feletti verzióra; - vagy állíts be egy egyedi SHA3-512 függvényt; - vagy hivatkozd be az n-other/php-sha3 vagy desktopd/SHA könyvtárat. Részletekért lásd a nav-online-invoice README-t.

Az üzenet a Util.php fájl generálta.
Ezt követően részletesebben átolvastam a program leírását, majd láttam, hogy szükség van külső modulok alkalmazására. Ekkor vettem észre, hogy a config.php fájlban található 2 db sor melyben include / található a külső modul(ok) meghívása.

// include_once(__DIR__ . "/../sha3-lib/bbSha3.php");
// include_once(__DIR__ . "/../sha3-lib/desktopdSHA3.php");

A until.php fáljban és a leírásban is megtalálható ennek 2 modulnak az elérhetősége:
https://github.com/n-other/php-sha3
https://notabug.org/desktopd/php-sha3-streamable

Sajnos egyik modulnál sem volt egyértelmű a leírás számomra, hogyan történik a modulok használata. Egyszerűen letöltöttem és feltöltöttem a szerverre, előtte szerveren létrehoztam sh3-lib/ mappát mivel a modulokban szereplő mappák nevével nem egyezett a config.php-ban megadott directory. A fájlok neve sem egyezett.  Nem volt világos számomra hogy a bbSha3.php file melyik az n-other/php-sha3 estén és melyik a desktopdSHA3.php fájl a desktopd/php-sha3-streamable esetén. Az sem volt világos számomra, hogy milyen mappákat kell létrehozni, kell-e új php filet létrehozni.

Amennyiben lehetséges kérnék egy teljes leírást arra vonatkozóan, hogy integrálhatóak a fenti modulok, vagy az a modul amelyikhez a legkevesebb leírás szükséges ahhoz, hogy működjön.
Hálás köszönettel:  Nagy Endre

**Comment by pzs** [comment]
Szia,

Örülök, hogy hasznát veszed :)
Tetszőleges helyre kell letölteni valamelyik modult, pl. [ezt](https://github.com/n-other/php-sha3/blob/master/src/Sha3.php), és ezt kell behivatkozni (include). Én pl. "sha3-lib" mappába töltöttem le ezt a fenti fájlt. Vagy használhatsz [composer](https://getcomposer.org/)-t is a modul telepítéséhez. Remélem, ez segít.

**Comment by endrus24** [comment]
Szia, Köszönöm a gyors választ.
Elnézést, de nekem nem nagyon világos ez a behivatkozás. 
Az alábbiakat csináltam:
1. Sha3.php filet- letöltöttem a gépemre ..
2. A szerveren készítettem egy sha3-lib mappát melybe feltöltöm az Sha3.php filet.
3. A config.php ben  az alábbi sort javítom erre:  include_once(__DIR__ . "/../sha3-lib/Sha3.php");

A fentieket csináltam és nem működött, Ugyanúgy azt a hibajelzést adta vissza.
A válaszod előre is köszönöm.

**Comment by pzs** [comment]
Pedig így kell működnie. Esetleg próbáld a [másikkal](https://notabug.org/desktopd/PHP-SHA3-Streamable/src/master/namespaced/desktopd/SHA3/Sponge.php).

**Comment by endrus24** [comment]
Szia!
Köszönöm a segítséged. Telepítettem SSL-t az oldalra és a config. php-ben átírtam a bbSha3.php-t Sha3.php-re. Valószínűleg az útvonalat és a file nevet írhattam el.
Most már működik! Még egyszer köszönöm!
