### ISSUE TITLE
queryInvoiceDigest térmék/szolgáltatás megjelenítése

### ISSUE THREAD

**Issue by utomi84** [pzs/nav-online-invoice#46]
Sziasztok. Előre is elnézést ha ez egy alapvető vagy ismert kérdés de a queryInvoiceDigest lekérdezés használata során van-e lehetőség arra, hogy a visszaadott XML-ben a termék/szolgáltatás szerepeljen? Tehát a kérdésem az lenne, hogy be lehet-e valahogy úgy paraméterezni a lekérdezést, hogy ez szerepeljen benne ? 
Ha jól láttam a QueryInvoiceDataRequestXml-lel ez megkapható információ de ahhoz konkrét számlaszám kell és nekem anélkül kellene. 
Illetve az adószám a visszakapott XML-ben 8 számjegyű, a megye kód és áfa besorolás sehogy sem kérhető vissza? 

Köszönöm szépen a válaszokat előre is.

**Comment by pzs** [comment]
Szia, a visszaadott XML a NAV-tól jön, így ezzel a kérdéssel őket tudod keresni, illetve az általuk kiadott dokumentációt tudod átnézni, a `nav-online-invoice` modul csak a kapcsolatot valósítja meg PHP-ban.
De röviden válaszolva, a `queryInvoiceDigest` tartalma tudtommal fix, és ha több infóra van szükséged, akkor az adott számlát kell lekérdezned a `queryInvoiceData` kéréssel számlaszám/adószám alapján.

**Comment by utomi84** [comment]
Rendben. Nagyon szépen köszönöm a válaszod.
