### ISSUE TITLE
Invoice XML

### ISSUE THREAD

**Issue by balicekt** [pzs/nav-online-invoice#47]
Hi, could anyone help me how to get XML of inovice? 

    $invoiceXml = simplexml_load_file(TEST_DATA_DIR . "invoice1.xml");
    $transactionId = $reporter->manageInvoice($invoiceXml, "CREATE");

I mean how create invoice1.xml from our internal data? 

Thank you very much for your help.

**Comment by pzs** [comment]
Hi,
you have to go though the API documentation: https://onlineszamla.nav.gov.hu/dokumentaciok (there is English version as well).
The second chapter describes the invoice XML itself.
This library is just for the communication (which is in the first chapter).

**Comment by balicekt** [comment]
I see now. Thank you very much :)
