### ISSUE TITLE
Hiányos supplierInfo és customerInfo a queryInvoiceData válaszban automatikus decode esetén

### ISSUE THREAD

**Issue by jmisel** [pzs/nav-online-invoice#48]
Szia!

Először is köszi a munkád.

A queryInvoiceData-val szeretnék számla adatot visszakapni (automatikus decode-dal) de a 3-as verziójú számláknál a válaszban hiányos a supplierInfo és a customerInfo.  

`$reporter->queryInvoiceData($invoiceNumberQuery, true)`

Az `InvoiceOperation::convertToXml` függvényében ez történik:

Adatok `base64_decode` után:

```
<invoiceHead>
	<supplierInfo>
		<supplierTaxNumber>
			<ns2:taxpayerId>KITÖLTVE</ns2:taxpayerId>
			<ns2:vatCode>KITÖLTVE</ns2:vatCode>
			<ns2:countyCode>KITÖLTVE</ns2:countyCode>
		</supplierTaxNumber>
		<supplierName>KITÖLTVE</supplierName>
		<supplierAddress>
			<ns2:detailedAddress>
				<ns2:countryCode>KITÖLTVE</ns2:countryCode>
				<ns2:postalCode>KITÖLTVE</ns2:postalCode>
				<ns2:city>KITÖLTVE</ns2:city>
				<ns2:streetName>KITÖLTVE</ns2:streetName>
				<ns2:publicPlaceCategory>KITÖLTVE</ns2:publicPlaceCategory>
				<ns2:number>KITÖLTVE</ns2:number>
				<ns2:floor>KITÖLTVE</ns2:floor>
				<ns2:door>KITÖLTVE</ns2:door>
			</ns2:detailedAddress>
		</supplierAddress>
	</supplierInfo>
	<customerInfo>
		<customerVatStatus>KITÖLTVE</customerVatStatus>
		<customerVatData>
			<customerTaxNumber>
				<ns2:taxpayerId>KITÖLTVE</ns2:taxpayerId>
				<ns2:vatCode>KITÖLTVE</ns2:vatCode>
				<ns2:countyCode>KITÖLTVE</ns2:countyCode>
			</customerTaxNumber>
		</customerVatData>
		<customerName>KITÖLTVE</customerName>
		<customerAddress>
			<ns2:detailedAddress>
				<ns2:countryCode>KITÖLTVE</ns2:countryCode>
				<ns2:postalCode>KITÖLTVE</ns2:postalCode>
				<ns2:city>KITÖLTVE</ns2:city>
				<ns2:streetName>KITÖLTVE</ns2:streetName>
				<ns2:publicPlaceCategory>KITÖLTVE</ns2:publicPlaceCategory>
				<ns2:number>KITÖLTVE</ns2:number>
			</ns2:detailedAddress>
		</customerAddress>
...
<invoiceHead>
```

`simplexml_load_string($data)` után:

```
[invoiceHead] => SimpleXMLElement Object
	(
		[supplierInfo] => SimpleXMLElement Object
			(
				[supplierTaxNumber] => SimpleXMLElement Object
					(
					)
				[supplierName] => KITÖLTVE
				[supplierAddress] => SimpleXMLElement Object
					(
					)
			)
		[customerInfo] => SimpleXMLElement Object
			(
				[customerVatStatus] => KITÖLTVE
				[customerVatData] => SimpleXMLElement Object
					(
						[customerTaxNumber] => SimpleXMLElement Object
							(
							)
					)
				[customerName] => KITÖLTVE
				[customerAddress] => SimpleXMLElement Object
					(
					)
			)
			...
	)
```

Talán a ns2-es névterekkel lesz a gond? 

Köszi a választ!

**Comment by pzs** [comment]
Szia,
az ott van az XML-ben, csak a print_r nem fogja kiírni a namespace-es részt SimpleXML esetén. Namaspace-eknek kell utánanézni SimpleXML-ben (pl. [itt](https://stackoverflow.com/questions/595946/parse-xml-with-namespace-using-simplexml) vagy [itt](https://www.php.net/manual/en/simplexmlelement.registerxpathnamespace.php)), vagy ha kényelmetlennek találod, esetleg eltávolítani (`XmlUtil::removeNamespaces($invoice)`).

**Comment by jmisel** [comment]
Csak így nem lesz teljes értékű a `queryInvoiceData` metódus dekódolás része, mert a névteres adatokat nem fogja dekódolni a számlából... A 2-es verziójú számláknál nincsenek névterek a `customerInfo` és `supplierInfo`-ban, míg a 3-asban vannak.

**Comment by pzs** [comment]
Ez már alkalmazás logika, s nem a `nav-online-invoice` interface-hez kapcsolódó téma, de ha van bármi ötleted, szívesen fogadom, akár annak megvalósítását is.

**Comment by jmisel** [comment]
Most már világos. Akkor marad a `XmlUtil::removeNamespaces($invoice)` használata. Köszi!
