### ISSUE TITLE
QueryInvoiceDigestRequest teljesítési dátum szűrés tól-ig

### ISSUE THREAD

**Issue by vrgblzs** [pzs/nav-online-invoice#49]
A QueryInvoiceDigestRequest-ben, ha egyszerre szeretnék szűrni a teljesítés dátum tól és ig értékére is, akkor ezt az xsd szerint megtehetem, pl.:
`<relationalQueryParams>
<invoiceDelivery><queryOperator>GTE</queryOperator><queryValue>2021-01-01</queryValue></invoiceDelivery><invoiceDelivery><queryOperator>LTE</queryOperator><queryValue>2021-01-18</queryValue></invoiceDelivery></relationalQueryParams>`
alakban. 

Ha átadok egy olyan tömböt a queryInvoiceDigest-nak, amiben a relationalQueryParams tömb, aminek elemei az invoiceDelivery tömbök, akkor az xml-be bekerül a relationalQueryParams tömb numerikus indexe is, mint node.

Ez talán elkerülhető lehet az XmlUtil::addChildArray-ban a 
`$node = (is_numeric($name)) ? $xmlNode : $xmlNode->addChild($name);` 
sorral. Kérdés, hogy jó-e így?

**Comment by pzs** [comment]
Szia! Köszi az észrevételt! Valóban erre nincs felkészítve az XmlUtil. Várhatóan holnapra javítom és készítek rá egy példát is.
Az általad írt javaslat működhet, ha megfelelően van átadva hozzá a tömb.
Addig is a request xml-t így ki tudod naplózni hívás után:
```php
$data = $reporter->getLastRequestData();
file_put_contents("request.xml", $data['requestBody']);
```

**Comment by pzs** [comment]
Módosítottam az `XmlUtil::addChildArray()` metódust, hogy megegyező néven is fel lehessen venni több gyerek elemet, illetve bővítettem a [példa](https://github.com/pzs/nav-online-invoice/blob/master/examples/queryInvoiceDigest.php#L17-L33) fájlt erre vonatkozó keresési feltétellel:

```php
$invoiceQueryParams = [
    // ...
    "relationalQueryParams" => [
        "invoiceDelivery" => [
            "queryOperator" => "GTE",
            "queryValue" => "2021-01-01",
        ],
        // Több feltétel esetén ugyanazon elemhez tömbben adjuk át a gyerek elemeket
        "paymentDate" => [
            [
                "queryOperator" => "GTE",
                "queryValue" => "2021-01-01",
            ],
            [
                "queryOperator" => "LTE",
                "queryValue" => "2021-01-28",
            ],
        ],
    ],
];
```

Következő v3.0.1-es release-t pedig jövő hét környékén tervezem elkészíteni, ha esetleg más visszajelzés is lenne addig.

**Comment by pzs** [comment]
Elkészült a [v3.0.1](https://github.com/pzs/nav-online-invoice/releases/tag/v3.0.1)-es release, mely tartalmazza ezt a javítást, így zárom az issue-t.
