### ISSUE TITLE
Technikai érvénytelenítés

### ISSUE THREAD

**Issue by elightsys** [pzs/nav-online-invoice#5]
Szia, nekem is nagyon tetszik a programod, profi munka. A példák alapján, sikeresen meg is történt a teszt számlák feltöltése. Lenne egy kérdésem és ne haragudj, hogy ide írok ez ügyben, de nem találtam más elérhetőségedet.

Nem találtam arra példát (vagy elkerülte a figyelmemet), hogy ha hibásan feltöltésre került egy számla, akkor hogyan technikai érvénytelenítést végrehajtani? 

Ha esetleg lenne időd és kedved szívesen venném a segítségedet az online számla adatszolgáltatási projektünk közreműködésében, természetesen anyagi ellenszolgáltatás ellenében.

A válaszodat előre is köszönöm!
Zoltán
onlineszamla@quitcomp.hu

**Comment by pzs** [comment]
Szia! Köszönöm a visszajelzést!

Valóban nincs rá példa, ha a `technicalAnnulment` flag-re gondolsz, ezt hamarosan pótlom, addig is röviden ezen példát kiegészítve: [examples/manageInvoice.php](https://github.com/pzs/nav-online-invoice/blob/master/examples/manageInvoice.php) `$invoices` példányon meg lehet hívni egy `$invoices->setTechnicalAnnulment(true);` metódust.

Esetleg nem tartom kizártnak, hogy érdemes lenne olyan funkciót elkészítenem, hogy `operation` értékétől függően automatikusan beállítsa a `technicalAnnulment` flag-et is a program.

Írok emailt is.

**Comment by pzs** [comment]
Szia! A `technicalAnnulment` flag beállítása a most kiadott v0.6.0-ás release-től automatikusan beállításra kerül az átadott `operation` értéke alapján, így azt már nem kell kézzel állítani ANNUL esetén.

Infó: https://github.com/pzs/nav-online-invoice/releases/tag/v0.6.0
