### ISSUE TITLE
queryInvoiceData - XML feldolgozási hiba

### ISSUE THREAD

**Issue by vasadibt** [pzs/nav-online-invoice#50]
Amennyiben queryInvoiceData meghívásakor engedélyezzük a számla dekódolását (returnDecodedInvoiceData=true), akkor a 
a számla XML-éből nem kerül kitakarításra a namespace-ek.
Hiányzik az InvoiceOperations::convertToXml függvényből a XmlUtil::removeNamespacesFromXmlString.

**Comment by pzs** [comment]
Szia, ez szándékos. A modul szándékosan nem módosítja a szakmai XML-t, az nem rá tartozik; de az alkalmazásod természetesen használhatja a fent említett XmlUtil metódust, ha namespace-ek nélküli XML-en akar dolgozni.

[Ennek](https://github.com/pzs/nav-online-invoice/blob/master/docs/xml_namespaces.md#namespace-ek-az-adat-sz%C3%A1mla-xml-ben) a doksi végén ezt biztosan meg is említettem pár szóban.

**Comment by vasadibt** [comment]
Köszönöm a segítséget, elkerülte a figyelmem.
