### ISSUE TITLE
NAV API v2.0-ról v3.0-ra átállás

### ISSUE THREAD

**Issue by PPetky** [pzs/nav-online-invoice#51]
Szia!
Felmerült bennem egy kérdés: most ugye a nav v2.0 API interface-t használjuk, március végétől meg a 3.0. Előjöhet-e olyan helyzet, hogy egy dokumentumot elküldtünk még a 2.0-n de már a módosítást vagy stornót (esetleg technikai érvénytelenítést) a 3.0-n? Nem fogja-e a 3.0-n küldött módosítás "hazavágni"  az előző dokumentunot?
Kösz.

**Comment by pzs** [comment]
Szia,
ez a kérdés a `nav-online-invoice` modultól független dolog, így kérlek, NAV-tól kérdezd meg, vagy esetleg prog.hu-s fórumon.
A `nav-online-invoice` modul csak a php-s kapcsolódást biztosítja.
