### ISSUE TITLE
Módosító számla

### ISSUE THREAD

**Issue by programozas** [pzs/nav-online-invoice#52]
Módosító számlát szeretnék csinálni 14_Tételadatok módosítása.xml alapján. Az alap számlához a következőket adom hozzá:
1:
<invoiceReference> 
<originalInvoiceNumber>2021/53</originalInvoiceNumber> 
<modifyWithoutMaster>false</modifyWithoutMaster> 
<modificationIndex>1</modificationIndex> 
</invoiceReference>
2:
<additionalInvoiceData> 
<dataName>2021/53</dataName> 
<dataDescription>visszáru</dataDescription> 
<dataValue>A  számla módosítása</dataValue> 
</additionalInvoiceData>
3:
<lineModificationReference>      
<lineNumberReference>3</lineNumberReference>       
<lineOperation>MODIFY</lineOperation>      
</lineModificationReference>

Erre a következő hibaüzenetet kapom:
- Eredeti számlára történő hivatkozás alapszámla esetén nem adható meg.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceReference
- Alapszámla esetén nem adható meg tételsor módosítás jelleg.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineModificationReference
–  Érték: 1
–  Számla sor: 1
- Alapszámla esetén nem adható meg tételsor módosítás jelleg.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineModificationReference
–  Érték: 1
–  Számla sor: 2

Mit csinálok rosszuk ?

**Comment by pzs** [comment]
Ez a kérdés a `nav-online-invoice` modultól független dolog, így kérlek, NAV-tól kérdezd meg, vagy más, ezzel kapcsolatos fórumon.
A `nav-online-invoice` modul csak a php-s kapcsolódást biztosítja.
