### ISSUE TITLE
manageAnnulment XsdValidationError

### ISSUE THREAD

**Issue by Mailmedve** [pzs/nav-online-invoice#53]
Hello!

$reporter->manageAnnulment küldéssel az alábbi hibát kapom:

"NavOnlineInvoice\XsdValidationError: Error: Element '{http://schemas.nav.gov.hu/OSA/3.0/data}InvoiceData': No matching global declaration available for the validation root. " 

ha ugyan ezt a tartalmat $reporter->manageInvoice küldöm, akkor probléma nélkül rögzíti a rendszer. 

Nem értem mi hiba oka.

Köszönöm a segítséget.

**Comment by tsamu** [comment]
Nem jó az xml amit érvénytelenítésre akarsz beküldeni.

Technikai érvénytelenítésre ezt az xmlt kell használni:
https://github.com/pzs/nav-online-invoice/blob/master/tests/testdata/invoice_annul.xml
