### ISSUE TITLE
Kötelező queryTransactionStatus

### ISSUE THREAD

**Issue by tsamu** [pzs/nav-online-invoice#54]
A https://onlineszamla.nav.gov.hu/technikai_kerdesek_valaszok oldalon az alábbi olvasgató:

> III. 9. kérdés: Figyeli-e, szankcionálja-e a NAV azt, hogy a /manageInvoice és a /queryInvoiceStatus operáció között mennyi idő telik el?
> 
> Az Art. 229. §-a alapján az adatszolgáltatási kötelezettség elmulasztása, késedelmes, hiányos, hibás vagy valótlan adattartalmú teljesítése esetén a kiszabható mulasztási bírság felső határa az érintett számlák, illetve a számlával egy tekintet alá eső okiratok számának és az általános bírságszabály szerinti bírság adózóra egyébként vonatkozó legmagasabb mértékének szorzata. **A Számlarendelet alapján az adatszolgáltatás akkor teljesül, amikor a sikeres feldolgozást a rendszer visszaigazolta. Mivel a visszaigazolás a /queryInvoiceStatus operációval történik meg, ameddig nem valósul meg a státusz lekérdezése, addig a jogszabály szerint nem történik meg az adatszolgáltatás.** A számlák feldolgozási státuszát visszaadó, az 1.0-ás és 1.1-es séma szerint /queryInvoiceStatus operáció a 2.0-ás sémától kezdve /queryTransactionStatus néven szerepel.
> 
> Mivel a számlák feldolgozása aszinkron működik, a beküldött adatszolgáltatás eredményére a jelenlegi számítások szerint 3–5 perc múlva érdemes visszakérdezni.

A fentiek értelmében szerintem érdemes lenne a README-ben is feltüntetni, hogy a queryTransactionStatus jogszabály szerint kötelező.

**Comment by pzs** [comment]
Köszi az észrevételt! A readme-vel nem a NAV dokumentációt vagy jogszabály elolvasását szeretném helyettesíteni, de felveszem ezt a figyelmeztetést a readme fájlba is a közeljövőben (addig pedig nyitva hagyom ezt az issue-t).

**Comment by tsamu** [comment]
Köszi. A NAV fejlesztői dokumentációban is csak egy mondat van erről és az ember hajlamos átsiklani ezen az apróságon.

> Az adatszolgáltatás addig nem tekinthető teljesítettnek, amíg a kliens az aszinkronfeldolgozás sikerességéről meg nem győződött és az adott számlához tartozó nyugtaüzenetet meg nem kapta.

**Comment by pzs** [comment]
>
