### ISSUE TITLE
Deprecated Error: Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by rrd108** [pzs/nav-online-invoice#58]
Importállásnál feljövő warning

```
In [/home/***/api/vendor/pzs/nav-online-invoice/src/NavOnlineInvoice/BaseRequestXml.php, line 57]

2022-03-08 11:10:59 notice: Deprecated (8192): Implicit conversion from float 1646737859.747168 to int loses precision in [/home/***/api/vendor/pzs/nav-online-invoice/src/NavOnlineInvoice/BaseRequestXml.php, line 57]

```

**Comment by hNczy** [comment]
Szia! 
Én is belefutottam. Már mergelve lett a masterbe. Ha lesz újabb release, akkor el fog tűnni ez a jelzés.
https://github.com/pzs/nav-online-invoice/pull/57

**Comment by pzs** [comment]
Igen, köszi, holnap reggelre elkészítem az új release-t az #57-es javítással.

**Comment by pzs** [comment]
El is készült a [v3.0.2](https://github.com/pzs/nav-online-invoice/releases/tag/v3.0.2)-es release, zárom ezt az issue-t.
