### ISSUE TITLE
regisztráció használathoz

### ISSUE THREAD

**Issue by RohamBilly** [pzs/nav-online-invoice#59]
Sziasztok,

a Használat szekcióban említitek, hogy "A használathoz a NAV oldalán megfelelő regisztrációt követően létrehozott technikai felhasználó adatainak beállítása szükséges!"

Egy jelenleg is működő weboldalon szeretném megoldani, hogy a regisztrálók adószámait ellenőrizni lehessen, hogy aktuálisak-e.

Hol kell pontosan regisztrálni?

Üdv: Billy

**Comment by rrd108** [comment]
https://onlineszamla.nav.gov.hu
