### ISSUE TITLE
Jóváírás

### ISSUE THREAD

**Issue by simisoma** [pzs/nav-online-invoice#60]
Sziasztok,

 ha egy számlából csak 1 tételt szeretnék jóváírni, ott az XML-ben mit kell megadjak?

Ha teljes számlát írok jóvá nem gond, de részt nem enged vagyis hibát dob vissza. --> Mert az érvénytelenít

- Érvénytelenítő számla nettó összege nem ad nullát az alapszámla módosításaival összesített nettó összegével összeadva.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceSummary/summaryNormal/invoiceNetAmount

Nekem csak 1 tétel vagy részben kellene jóváírjak.

Ha csak CREATE számla értéke negatív akkor pedig üzleti hibát dob a vissza a NAV. (mert ez a verzió is jó lenne nekem) - Mi a helyes eljárás?

Előre is köszönöm! 
Soma

**Comment by pzs** [comment]
Szia, zárom ezt az issue-t: a szakmai XML összeállításában más fórumon tudnak segíteni (pl. prog.hu vagy NAV).
