### ISSUE TITLE
DTB

### ISSUE THREAD

**Issue by Diego65** [pzs/nav-online-invoice#62]
Hello,
Lesz esetleg a pénztárgép listák lekérdezésére is hasonló kis program?

**Comment by pzs** [comment]
Szia,
Én nem tervezek készíteni (jelenleg nekem nem kell dolgozni pénztárgépes API-val, illetve nem is ismerem).

**Comment by rrd108** [comment]
Itt van a NAVos infó hozzá: https://github.com/nav-gov-hu/Online-Cash-Register-Logfile

Ha lesz rá időm lehet ránézek, hogy mit lehet vele kezdeni.

**Comment by Diego65** [comment]
Nekem, ahogy átfutottam rajta, úgy tünt, hogy vannak közös részek benne, vagyis a nav-online redszerhez irt program bizonyos részei használhatók lennének a pénztárgépe lekérdezésnél is, ezért érdeklődtem.
Biztosan ezt is sokan használnák lekérdezésekhez, hibakeresésre.
