### ISSUE TITLE
tokenExchange forbidden választ ad

### ISSUE THREAD

**Issue by oliverIbookr** [pzs/nav-online-invoice#64]
Amennyiben egy olyan technikai felhasználót hozunk létre a NAV rendszerében, akinél csak a "Számlák lekérdezése" jogosultság elérhető, a "Számlák kezelése" pedig nem, akkor a token exchange nem hívható meg. Ez azért baj, mert elméletileg a tokenExchange funkciója, hogy a technikai felhasználó adatait és a programot teszteljük. A queryInvoiceDigest működik abban az esetben is, hogyha csak a "Számlák lekérdezése" jogosultság érhető el.
A kérdésem az lenne, hogy normális-e, hogy a tokenExchange forbidden választ ad, és ehelyett inkább queryInvoiceDigest-et használjuk a technikai felhasználó adatainak ellenőrzésére?

**Comment by pzs** [comment]
Köszi az infót! A technikai felhasználó adatainak tesztelésére csak én javasoltam ezt a fajta módszert (a NAV kézikönyvben tudtommal nincs ilyen - így normális működésnek tartom), de ez alapján ki fogom egészíteni a README-t. Addig is nyitva hagyom ezt az issue-t.
