### ISSUE TITLE
Számla törzsadatai alapján a tételek lekérdezése

### ISSUE THREAD

**Issue by juhaszraymond** [pzs/nav-online-invoice#66]
Sziasztok,

Ti hogy oldottátok meg, hogy mikor lekérem a bejövő számlákat, akkor a tételeket is lássam? Szeretném naponra többször lekérni a bejövő számlákat, tételekkel. Ezt adatbázisba menteném.

Hogy célszerű megoldani?

Köszi a helpet!

**Comment by szecsenyizoltan** [comment]
A számlát json-be konvertálom és egy mezőben tárolom, míg a fejléc adatait adatonként/mezőnként rögzítem. Az eljárás oka, hogy csak számlalikvidációra használom az információt. Szóval nem ez a legjobb megoldás, hanem a felhasználáshoz mérten elegendő az én esetemben.

**Comment by imanzuk** [comment]
Lekérem a számlák fejléc adatait a QueryInvoiceDigestRequest használatával, majd az egyes számlákhoz a tételeket a QueryInvoiceDataRequest használatával.

**Comment by juhaszraymond** [comment]
Köszönöm így tettem én is. Csak gondoltam valakinél beváltan van-e valami más ötlete!
