### ISSUE TITLE
CurlError: Connection error. CURL error code: 56

### ISSUE THREAD

**Issue by rrd108** [pzs/nav-online-invoice#67]
Nem tudom, hogy a NAV rendszer döglődik, vagy bevezettek valami új limitet.

1mp-es delay-jel kérek le számlákat és kb 3 napja olyan 50-60 számla után elpusztul.

`NavOnlineInvoice\CurlError: Connection error. CURL error code: 56`

**Comment by kisspandur** [comment]
A hétvégén (és előtte is) elég nagy leállások voltak.
https://nav.gov.hu/ugyfeliranytu/arveres/uzemszunet_EAF

**Comment by rrd108** [comment]
ok, szóval náluk van valami.
